export const GET_WEATHER_START = 'GET_WEATHER_START';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE';

export const GET_COORDS_SUCCESS = 'GET_COORDS_SUCCESS';
export const GET_WEATHER_BY_COORDS = 'GET_WEATHER_BY_COORDS';
export const GET_WEATHER_BY_NAME = 'GET_WEATHER_BY_NAME';

export const GET_FORECAST = 'GET_FORECAST';
export const GET_FORECAST_AUTO = 'GET_FORECAST_AUTO';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_FAILURE = 'GET_FORECAST_FAILURE';

export const GET_HOURLY_BY_NAME = 'GET_HOURLY_BY_NAME';
export const GET_HOURLY_BY_NAME_SUCCESS = 'GET_HOURLY_BY_NAME_SUCCESS';
export const GET_HOURLY_BY_NAME_FAILURE = 'GET_HOURLY_BY_NAME_FAILURE';

export const GET_SEARCH_LIST_START = 'GET_SEARCH_LIST_START';
export const GET_SEARCH_LIST_SUCCESS = 'GET_SEARCH_LIST_SUCCESS';
export const GET_SEARCH_LIST_FAILURE = 'GET_SEARCH_LIST_FAILURE';
export const GET_SEARCH_LIST = 'GET_SEARCH_LIST';

export const SET_ACTIVE_SEARCH_LIST_ELEMENT = 'SET_ACTIVE_SEARCH_LIST_ELEMENT';
export const SET_ACTIVE_SEARCH_LIST_ELEMENT_BY_MOUSEOVER = 'SET_ACTIVE_SEARCH_LIST_ELEMENT_BY_MOUSEOVER';

export const SET_ERROR = 'SET_ERROR';
